import Head from 'next/head'
import axios from 'axios'
import { useEffect } from 'react'
import { useDispatch } from 'react-redux'
import { setUser } from '../features/user/userSlice'
import { setChatList } from '../features/chat/chatListSlice'

import LoginView from '../components/LoginView'
import PanelLeftSide from '../components/PanelLeftSide'
import PanelRightSide from '../components/PanelRightSide'

export default function Home({ userData, chatListData }) {
	const dispatch = useDispatch()

	useEffect(() => {
		if (userData) {
			dispatch(setUser(userData))
		}
		if (chatListData) {
			dispatch(setChatList(chatListData))
		}
	}, [userData, chatListData, dispatch])

	return (
		<div>
			<Head>
				<title>WhatsClon</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{userData ? (
				<div className=" flex justify-center ">
					<div className="absolute  flex justify-end 2xl:top-[19px] 2xl:h-[calc(100%-38px)] 2xl:w-[calc(100%-38px)] 2xl:max-w-[1600px] h-full w-full">
						<PanelLeftSide />
						<PanelRightSide />
					</div>
				</div>
			) : (
				<LoginView />
			)}
		</div>
	)
}

export async function getServerSideProps(ctx) {
	const { token, user_id } = ctx.req.cookies

	if (token && user_id) {
		try {
			const config = {
				headers: {
					Authorization: `Bearer ${token}`,
				},
			}

			const { data } = await axios.get(
				`${process.env.BASE_URL_API}/api/users/findById/${user_id}`,
				config
			)

			if (data === null) {
				return { props: { userData: null } }
			}

			const userData = {
				...data,
				token,
			}

			try {
				const chatlist = await axios.get(`${process.env.BASE_URL_API}/api/chats/${user_id}`, config)
				const chatListData = chatlist.data
				return { props: { userData, chatListData } }
			} catch (err) {}
			return { props: { userData } }
		} catch (err) {
			console.log(err)
			return { props: {} }
		}
	}
	return {
		props: {}, // will be passed to the page component as props
	}
}
